version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.26
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ExamenDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

  app:
    build: .
    container_name: springboot-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/ExamenDatabase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysqldb

volumes:
  mysqldb_data: